### ISSUE TITLE
What type of LICENSE does this project have?

### ISSUE THREAD

**Issue by rozzzly** [sindresorhus/-#16]
I want to try to convince my CEO that we should drop `joomla.NET` and switch to `-` because while they have feature parity, `-` is _a lot lighter_, and has even been updated within the past decade which is a plus.

However, my company has **strict** rules about licensing in our projects; we can only use open source dependencies that are licensed with "**BSD+ Patents**". My boss says Facebook uses that we have to too. _(Sucks that we also have to support Microsoft Internet Explorer 3.03 which is incompatible with `React` 😭)_ 

We'd appreciate hearing back from a member of the `-` team within the next fortnight if possible. Thanks! keep up all great work.

> PS: it would be really convenient for us if you could `.rar` releases and host the project on SourceForge.

**Comment by sindresorhus** [comment]
It's available under the Unicorn License:

> Permission is hereby granted, free of charge, to any person obtaining a copy of this project, subject to the following condition: You must send the author a unicorn-themed card in the mail.

**Comment by rozzzly** [comment]
Will an email with an `ascii-unicorn` *(there's a new repo for you btw)* suffice?

I'd appreciate attribution for that new repo.

> Guess what I just did?
>
> What?
>
> Gave @sindresorhus inspiration to start a popular new package
>
> gtfo Patrick
>
> No! Seriously, check it out: https://github.com/sindresorhus/ascii-unicorn
>
> ...
>
> > Adapted from @rozzzly's suggestion that I make the cows horny
>
> ...
> **GTFO Patrick**
