### ISSUE TITLE
Tired of write code in PLAIN TEXT? Try Cirru!

### ISSUE THREAD

**Issue by chenyong** [sindresorhus/-#17]
[removed spam]

**Comment by rozzzly** [comment]
I'm sure advertising like that here on GitHub will help you make you're language real popular. You might even make _2nd_ page of
 https://google.com/search?q=shitty+programming+languages

**Comment by chenyong** [comment]
I don't mind people call it whatever. As long as Cirru helps people save time in generating code, I feel my work rewarded. Please give it a try.
