### ISSUE TITLE
?

### ISSUE THREAD

**Issue by zrosenbauer** [sindresorhus/-#21]
?

**Comment by sindresorhus** [comment]
❓

**Comment by Hoishin** [comment]
![thinkingemogif](https://user-images.githubusercontent.com/28832095/37884365-9b5cd212-30ea-11e8-9a77-3401d0843046.gif)

**Comment by zrosenbauer** [comment]
![image](https://user-images.githubusercontent.com/3486461/38139479-2a5c94e0-33f5-11e8-9e23-f9cf636e984e.png)

**Comment by SirMcPotato** [comment]
@zrosenbauer Yes?
