### ISSUE TITLE
How this repository can be used?

### ISSUE THREAD

**Issue by vitalkanev** [sindresorhus/-#5]
No files :eyes:

**Comment by aashutoshrathi** [comment]
​

**Comment by sindresorhus** [comment]
![unicorn20](https://user-images.githubusercontent.com/170270/37332763-35aa4306-26da-11e8-8d12-f60e4cf8d06e.gif)

**Comment by devdot4** [comment]
![giphy_s](https://user-images.githubusercontent.com/15527358/37341157-cdc061a0-2696-11e8-9620-d57d9a0db106.gif)

**Comment by devdot4** [comment]
![IMG](https://media.giphy.com/media/xUA7b7iSKUVXNEahig/source.gif)

**Comment by devdot4** [comment]
![source 1](https://user-images.githubusercontent.com/15527358/37341279-3c736be2-2697-11e8-8c2b-49c760321bba.gif)

**Comment by apertureless** [comment]
![shia-labeouf-12NUbkX6p4xOO4](https://media0.giphy.com/media/12NUbkX6p4xOO4/giphy.gif?cid=e1bb72ff5aa81ddd4242597a67276636)
