### ISSUE TITLE
[bug report] I imported this lib but nothing happend

### ISSUE THREAD

**Issue by Dafrok** [sindresorhus/-#6]
### Version

龘䶛䨻䎱㸞蚮䡶䴞䴝䯬䬛䰕㹚

### Expected

㱎䖘䵈䶁䘔䶑䘓鋱䩳䵷㒪䪉䉥

### Actual

䥸䝟䳮䟑䎘䫱䉷䰯䕈䟐䬝

### Reproduction

```
䥰龘䰕䘋㽌䇁䵄䵻䬛蟿䆉㖀
```

**Comment by diegohaz** [comment]
So we speak the same language.

![image](https://user-images.githubusercontent.com/3068563/37373415-47b933e8-26f5-11e8-9faf-bec61484ff88.png)
